version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      npm-dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action*"
      actions-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
